### ISSUE TITLE
Handling of { and }

### ISSUE THREAD

**Issue by michiexile** [dougalsutherland/sublime-stan#5]
According to the Stan language grammar, a statement can be a `{`/`}`-delimited block. In particular, this means that the following is a valid piece of Stan code:

```
model {
  y[1] ~ dnorm(0, 1e-5);

  for (i in 2:N) {
    y[i] ~ dnorm(mu[i], tau);
    mu[i] <- w0 + w1*y[i-1] + eps[i-1];
    eps[i] <- y[i] - mu[i];
  }

  w0 ~ dnorm (0, 1e-6);
}
```

However, the syntax highlighting marks everything after the `for`-block as erroneous.

_Expected behaviour_: `{`/`}` matching even if none of the top-level keywords precede the brackets.

**Comment by dougalsutherland** [comment]
Huh, I thought this worked. I no longer use Stan regularly, but I'll try to look into it soon....

**Comment by dougalsutherland** [comment]
Obviously I didn't look into this "soon" – sorry about that – but this works for me in the current version.
